import { BarChart3, CalendarRange, Download, ReceiptText, ShoppingBag, TrendingUp, WalletCards } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { MetricCard } from '../components/features/dashboard/MetricCard'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Input } from '../components/ui/FormField'
import { PageHeader } from '../components/ui/PageHeader'
import { useWorkspace } from '../hooks/useWorkspace'
import { buildExpenseDistribution, buildMonthlyProfit, calculateMetrics, type DateRange } from '../utils/analytics'
import { formatCurrency } from '../utils/format'
import { exportReport } from '../services/csv'

const firstDay = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01` }
const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'America/Lima' })
const parseRange = (from: string, to: string): DateRange => ({ from: from ? new Date(`${from}T00:00:00`) : null, to: to ? new Date(`${to}T23:59:59.999`) : null })

export function ReportsPage() {
  const { data } = useWorkspace(); const [from, setFrom] = useState(firstDay); const [to, setTo] = useState(today)
  const range = useMemo(() => parseRange(from, to), [from, to]); const metrics = useMemo(() => data ? calculateMetrics(data, range) : null, [data, range]); const categoryData = useMemo(() => metrics ? buildExpenseDistribution(metrics.filteredExpenses) : [], [metrics]); const monthly = useMemo(() => metrics ? buildMonthlyProfit(metrics.filteredSales, metrics.filteredExpenses) : [], [metrics])
  if (!metrics) return null
  return <div className="space-y-7"><PageHeader eyebrow="Análisis" title="Reportes" description="Selecciona un periodo para entender el rendimiento de KOVA." actions={<Button variant="secondary" onClick={() => data && exportReport(data, range, `${from}-${to}`)}><Download className="size-4" />Exportar reporte</Button>} />
    <Card className="flex flex-col gap-4 p-4 sm:flex-row sm:items-end"><div className="grid flex-1 gap-3 sm:max-w-lg sm:grid-cols-2"><Input label="Desde" type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /><Input label="Hasta" type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></div><div className="flex items-center gap-2 pb-2 text-xs font-semibold text-stone-400"><CalendarRange className="size-4" />Los datos se actualizan automáticamente</div></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Ingresos" value={formatCurrency(metrics.income)} icon={TrendingUp} tone="positive" /><MetricCard label="Egresos" value={formatCurrency(metrics.expenses)} icon={ReceiptText} /><MetricCard label="Ganancia" value={formatCurrency(metrics.profit)} icon={WalletCards} tone={metrics.profit < 0 ? 'negative' : 'positive'} /><MetricCard label="Ticket promedio" value={formatCurrency(metrics.averageTicket)} icon={ShoppingBag} /></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReportValue label="Ventas" value={String(metrics.salesCount)} /><ReportValue label="Unidades vendidas" value={String(metrics.units)} /><ReportValue label="Producto más vendido" value={metrics.topProduct} /><ReportValue label="Aportes totales" value={formatCurrency(metrics.totalContributions)} /></section>
    <Card className="p-5 sm:p-6"><div className="mb-6"><h2 className="font-display font-bold">Ganancia por mes</h2><p className="mt-1 text-xs text-stone-400">Ingresos, egresos y resultado neto</p></div><div className="h-72">{monthly.length ? <ResponsiveContainer width="100%" height="100%"><ComposedChart data={monthly} margin={{ left: -15, right: 10 }}><CartesianGrid vertical={false} stroke="#e7e5e4" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#a8a29e' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#a8a29e' }} /><Tooltip formatter={(value) => formatCurrency(Number(value))} contentStyle={{ borderRadius: 12, borderColor: '#e7e5e4', fontSize: 12 }} /><Bar dataKey="ingresos" fill="#171717" radius={[5, 5, 0, 0]} /><Bar dataKey="egresos" fill="#d6d3d1" radius={[5, 5, 0, 0]} /><Line dataKey="ganancia" stroke="#dc2626" strokeWidth={2} dot={{ r: 3 }} /></ComposedChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm font-semibold text-stone-400"><BarChart3 className="mr-2 inline size-5" />Sin datos</div>}</div></Card>
    <section className="grid gap-4 lg:grid-cols-2"><Card className="overflow-hidden"><div className="border-b border-stone-100 px-5 py-5"><h2 className="font-display font-bold">Gastos por categoría</h2></div><div className="divide-y divide-stone-100">{categoryData.map((item) => <div key={item.name} className="flex items-center justify-between px-5 py-3.5"><span className="text-sm font-semibold">{item.name}</span><strong className="text-sm">{formatCurrency(item.value)}</strong></div>)}{!categoryData.length && <p className="p-6 text-center text-sm text-stone-400">Sin gastos en el periodo.</p>}</div></Card><Card className="p-5"><h2 className="font-display font-bold">Aportes del periodo</h2><div className="mt-5 space-y-4"><Contribution label="Fabricio" amount={metrics.fabricio} total={metrics.totalContributions} /><Contribution label="Daniela" amount={metrics.daniela} total={metrics.totalContributions} /></div><div className="mt-6 rounded-xl bg-stone-50 p-4"><p className="text-xs text-stone-400">Diferencia de aportes</p><p className="mt-1 font-display text-xl font-extrabold">{formatCurrency(metrics.contributionDifference)}</p><p className="mt-1 text-xs text-stone-400">Dato informativo; no representa una deuda.</p></div></Card></section>
  </div>
}
function ReportValue({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="text-xs font-semibold text-stone-400">{label}</p><p className="mt-2 truncate font-display text-xl font-extrabold">{value}</p></Card> }
function Contribution({ label, amount, total }: { label: string; amount: number; total: number }) { const percent = total ? Math.round(amount / total * 100) : 0; return <div><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{label}</span><span className="font-extrabold">{formatCurrency(amount)}</span></div><div className="h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-stone-950" style={{ width: `${percent}%` }} /></div></div> }
