import { CheckCircle2, Database, Download, ExternalLink, FileDown, FileSpreadsheet, MessageCircle, RefreshCw, ShieldCheck, Upload, Users } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { ImportCsvModal } from '../components/features/import/ImportCsvModal'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { ConfirmDialog } from '../components/ui/ConfirmDialog'
import { Input } from '../components/ui/FormField'
import { PageHeader } from '../components/ui/PageHeader'
import { useAuth } from '../hooks/useAuth'
import { useWorkspace } from '../hooks/useWorkspace'
import { downloadExpensesTemplate, downloadSalesTemplate, exportExpenses, exportHistory, exportReport, exportSales } from '../services/csv'
import { presetRange } from '../utils/analytics'

export function SettingsPage() {
  const { user } = useAuth(); const { data, service, refresh } = useWorkspace(); const [importType, setImportType] = useState<'sales' | 'expenses'>(); const [saving, setSaving] = useState(false); const [resetOpen, setResetOpen] = useState(false); const [whatsappNumber, setWhatsappNumber] = useState(data?.business.whatsappNumber ?? '51')
  if (!data) return null
  const saveWhatsapp = async () => {
    const normalized = whatsappNumber.replace(/\D/g, '')
    if (!/^[1-9][0-9]{8,14}$/.test(normalized)) { toast.error('Ingresa el número con código de país, solo dígitos.'); return }
    setSaving(true)
    try { await service.updateBusinessContact(normalized); await refresh(); setWhatsappNumber(normalized); toast.success('WhatsApp del catálogo actualizado.') }
    catch (reason) { toast.error(reason instanceof Error ? reason.message : 'No se pudo guardar el número.') }
    finally { setSaving(false) }
  }
  const resetDemo = async () => { if (!service.resetDemo) return; setSaving(true); await service.resetDemo(); await refresh(); setSaving(false); setResetOpen(false); toast.success('Datos demo restablecidos.') }
  return <div className="space-y-7"><PageHeader eyebrow="Workspace" title="Configuración" description="Datos, seguridad y preferencias generales de KOVA." />
    <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-stone-100"><Database className="size-5" /></span><div><h2 className="font-display font-bold">Producción bajo pedido</h2><p className="mt-1 text-xs text-stone-400">Flujo de trabajo de KOVA</p></div></div><div className="mt-6 rounded-2xl border border-stone-200 p-4"><p className="text-sm font-bold">Medida de muñeca obligatoria</p><p className="mt-1 text-xs leading-5 text-stone-500">Cada pulsera se elabora después de registrar la medida del cliente. Por eso el sistema no administra existencias de productos terminados.</p></div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-stone-100"><ShieldCheck className="size-5" /></span><div><h2 className="font-display font-bold">Estado del sistema</h2><p className="mt-1 text-xs text-stone-400">Conexión y protección</p></div></div><div className="mt-6 space-y-3"><Status label="Almacenamiento" value={user?.isDemo ? 'Navegador local' : 'Supabase PostgreSQL'} /><Status label="Seguridad" value={user?.isDemo ? 'Modo demostración' : 'RLS habilitado'} /><Status label="Moneda" value="PEN · Sol peruano" /><Status label="Zona horaria" value="America/Lima" /></div></Card></section>
    <Card className="p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><MessageCircle className="size-5" /></span><div><h2 className="font-display font-bold">Catálogo y WhatsApp</h2><p className="mt-1 max-w-xl text-xs leading-5 text-stone-400">Los botones de compra enviarán modelo, ciudad y la medida cuando corresponda.</p></div></div><div className="flex w-full flex-col gap-3 sm:flex-row lg:w-auto"><Input label="Número con código de país" value={whatsappNumber} onChange={(event) => setWhatsappNumber(event.target.value)} placeholder="51987654321" hint="Solo dígitos; para Perú comienza con 51." /><div className="flex items-end gap-2"><Button loading={saving} onClick={() => void saveWhatsapp()}>Guardar</Button><a href="/catalogo" target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 rounded-xl border border-stone-200 px-4 text-sm font-bold hover:bg-stone-50">Ver catálogo<ExternalLink className="size-4" /></a></div></div></div></Card>
    <Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-stone-100"><Upload className="size-5" /></span><div><h2 className="font-display font-bold">Importar desde Excel / CSV</h2><p className="mt-1 text-xs text-stone-400">Descarga una plantilla, complétala y revisa la vista previa.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><ImportCard title="Ventas" description="Fecha, producto, medida de muñeca, cantidad, precio y pago" onTemplate={downloadSalesTemplate} onImport={() => setImportType('sales')} /><ImportCard title="Gastos" description="Concepto, categoría, responsable y aportes" onTemplate={downloadExpensesTemplate} onImport={() => setImportType('expenses')} /></div></Card>
    <Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-stone-100"><FileDown className="size-5" /></span><div><h2 className="font-display font-bold">Exportar y respaldar</h2><p className="mt-1 text-xs text-stone-400">Tus datos siempre pueden salir de KOVA Control.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><ExportButton label="Ventas CSV" onClick={() => exportSales(data)} /><ExportButton label="Gastos CSV" onClick={() => exportExpenses(data)} /><ExportButton label="Historial CSV" onClick={() => exportHistory(data)} /><ExportButton label="Reporte mensual" onClick={() => exportReport(data, presetRange('month'), 'mes-actual')} /></div></Card>
    <Card className="overflow-hidden"><div className="flex items-start gap-3 border-b border-stone-100 px-5 py-5 sm:px-6"><span className="grid size-10 place-items-center rounded-xl bg-stone-100"><Users className="size-5" /></span><div><h2 className="font-display font-bold">Miembros de KOVA</h2><p className="mt-1 text-xs text-stone-400">Ambos ven los mismos datos</p></div></div><div className="divide-y divide-stone-100">{data.members.map((member) => <div key={member.profileId} className="flex items-center gap-3 px-5 py-4 sm:px-6"><span className="grid size-9 place-items-center rounded-full bg-stone-950 text-sm font-extrabold text-white">{member.displayName.charAt(0)}</span><div className="flex-1"><p className="text-sm font-bold">{member.displayName}</p><p className="text-xs text-stone-400">{member.role === 'owner' ? 'Propietario' : member.role === 'admin' ? 'Administrador' : 'Miembro'}</p></div><Badge tone="success">Activo</Badge></div>)}</div></Card>
    {user?.isDemo && <Card className="flex flex-col gap-4 border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display font-bold text-amber-950">Restablecer datos demo</h2><p className="mt-1 text-sm text-amber-800">Borra tus cambios locales y recupera los valores originales.</p></div><Button variant="secondary" onClick={() => setResetOpen(true)}><RefreshCw className="size-4" />Restablecer demo</Button></Card>}
    {importType && <ImportCsvModal type={importType} onClose={() => setImportType(undefined)} />}<ConfirmDialog open={resetOpen} onClose={() => setResetOpen(false)} onConfirm={resetDemo} loading={saving} title="¿Restablecer los datos demo?" description="Se eliminarán los cambios realizados en este navegador y volverán los datos iniciales." confirmLabel="Restablecer" />
  </div>
}
function Status({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 text-sm"><span className="text-stone-500">{label}</span><span className="flex items-center gap-1.5 font-bold"><CheckCircle2 className="size-4 text-emerald-600" />{value}</span></div> }
function ImportCard({ title, description, onTemplate, onImport }: { title: string; description: string; onTemplate: () => void; onImport: () => void }) { return <div className="rounded-2xl border border-stone-200 p-4"><FileSpreadsheet className="size-5 text-stone-500" /><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-stone-400">{description}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={onImport}>Importar</Button><Button size="sm" variant="ghost" onClick={onTemplate}><Download className="size-4" />Plantilla</Button></div></div> }
function ExportButton({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex items-center gap-2 rounded-xl border border-stone-200 p-3 text-left text-sm font-bold transition hover:border-stone-400 hover:bg-stone-50"><Download className="size-4 text-stone-400" />{label}</button> }
